AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an EC2 ImageBuilder component for installing Prometheus agent'

Parameters:
  HpcRecipesS3Bucket:
    Type: String
    Default: aws-hpc-recipes
    Description: S3 bucket containing HPC Recipes assets
  
  HpcRecipesBranch:
    Type: String
    Default: main
    Description: Branch name for HPC Recipes assets

Resources:
  PrometheusAgentInstallerComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: PrometheusAgentInstaller
      Platform: Linux
      Version: 1.0.0
      Description: Installs and configures Prometheus agent for PCS clusters
      Data: !Sub |
        name: PrometheusAgentInstaller
        description: Installs and configures Prometheus agent for PCS clusters
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: DownloadScripts
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      mkdir -p /tmp/scripts
                      # cd /tmp/scripts
                      # curl -fsSL "https://raw.githubusercontent.com/Soham-G/aws-hpc-recipes/pcs-observability/recipes/pcs/hpc_ready_ami/assets/scripts/common.sh" -o "common.sh"
                      # curl -fsSL "https://raw.githubusercontent.com/Soham-G/aws-hpc-recipes/pcs-observability/recipes/pcs/hpc_ready_ami/assets/scripts/install-prometheus-agent.sh" -o "install-prometheus-agent.sh"
                      # aws s3 cp s3://soham-hpc-stockholm-assets/hpc-recipes-temp/scripts/common.sh common.sh
                      # aws s3 cp s3://soham-hpc-stockholm-assets/hpc-recipes-temp/scripts/install-prometheus-agent.sh install-prometheus-agent.sh
              - name: DownloadCommon
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/common.sh
                    destination: /tmp/scripts/common.sh
              - name: DownloadInstaller
                action: WebDownload
                inputs:
                  - source: https://${HpcRecipesS3Bucket}.s3.us-east-1.amazonaws.com/${HpcRecipesBranch}/recipes/pcs/hpc_ready_ami/assets/scripts/install-prometheus-agent.sh
                    destination: /tmp/scripts/install-prometheus-agent.sh
              - name: InstallPrometheusAgent
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      cd /tmp/scripts
                      chmod +x *.sh
                      # Note: The prometheus endpoint is configured externally to this setup, with a separate cloudformation template, and this script expects to find the parameter in SSM
                      PROMETHEUS_ENDPOINT=$(aws ssm get-parameter --name "/pcs/observability/pcs-prometheus/endpoint" --region ${AWS::Region} --query "Parameter.Value" --output text || echo "http://localhost:9090")
                      ./install-prometheus-agent.sh --endpoint "${!PROMETHEUS_ENDPOINT}" --gpu-exporter auto --efa-exporter auto --region ${AWS::Region}
              - name: Cleanup
                action: ExecuteBash
                inputs:
                  commands:
                    - |
                      rm -rf /tmp/scripts

Outputs:
  ComponentArn:
    Description: ARN of the created EC2 ImageBuilder component
    Value: !GetAtt PrometheusAgentInstallerComponent.Arn
  ImageBuilderComponent:
    Value: !Ref PrometheusAgentInstallerComponent
